### ISSUE TITLE
bundle.sh: ".stack-work/dist/x86_64-osx/Cabal-1.22.8.0_ghcjs/: does not exist"

### ISSUE THREAD

**Issue by runeksvendsen** [agrafix/react-flux-example#1]
Hi

I'm in OSX, trying to build this example, and I get an error from the `stack build` step in `bundle.sh`, because it can't find stuff inside `.stack-work/dist`.

I would love some help on this, as I have no idea what's supposed to be inside `.stack-work/dist`.

Relevant logs:

```shell
$ npm run-script prepare

> react-flux-example@1.0.0 prepare /Users/rune/IdeaProjects/react-flux-example
> chmod +x prepare.sh bundle.sh && ./prepare.sh

stack will use a sandboxed GHCJS it installed
For more information on paths, see 'stack path' and 'stack exec env'
To use this GHCJS and packages outside of a project, consider using:
stack ghc, stack ghci, stack runghc, or stack exec

$ stack path | grep stack-work
local-pkg-db: /Users/rune/IdeaProjects/react-flux-example/.stack-work/install/x86_64-osx/lts-5.12/ghcjs-0.2.0_ghc-7.10.3/pkgdb
ghc-package-path: /Users/rune/IdeaProjects/react-flux-example/.stack-work/install/x86_64-osx/lts-5.12/ghcjs-0.2.0_ghc-7.10.3/pkgdb:/Users/rune/.stack/snapshots/x86_64-osx/lts-5.12/ghcjs-0.2.0_ghc-7.10.3/pkgdb:/Users/rune/.ghcjs/x86_64-darwin-0.2.0-7.10.3/ghcjs/package.conf.d
local-install-root: /Users/rune/IdeaProjects/react-flux-example/.stack-work/install/x86_64-osx/lts-5.12/ghcjs-0.2.0_ghc-7.10.3
local-doc-root: /Users/rune/IdeaProjects/react-flux-example/.stack-work/install/x86_64-osx/lts-5.12/ghcjs-0.2.0_ghc-7.10.3/doc
dist-dir: .stack-work/dist/x86_64-osx/Cabal-1.22.8.0_ghcjs
local-hpc-root: /Users/rune/IdeaProjects/react-flux-example/.stack-work/install/x86_64-osx/lts-5.12/ghcjs-0.2.0_ghc-7.10.3/hpc

$ ls .stack-work/dist/x86_64-osx/Cabal-1.22.8.0_ghcjs
ls: .stack-work/dist/x86_64-osx/Cabal-1.22.8.0_ghcjs: No such file or directory

$ ls .stack-work/
install logs

$ npm run-script make

> react-flux-example@1.0.0 make /Users/rune/IdeaProjects/react-flux-example
> ./bundle.sh

Stack build ...
Ignoring that the GHCJS boot package "scientific" has a different version, 0.3.3.8, than the resolver's wanted version, 0.3.4.6
Ignoring that the GHCJS boot package "case-insensitive" has a different version, 1.2.0.4, than the resolver's wanted version, 1.2.0.6
Ignoring that the GHCJS boot package "hashable" has a different version, 1.2.3.2, than the resolver's wanted version, 1.2.4.0
Ignoring that the GHCJS boot package "async" has a different version, 2.0.1.6, than the resolver's wanted version, 2.1.0
Ignoring that the GHCJS boot package "text" has a different version, 1.2.1.1, than the resolver's wanted version, 1.2.2.1
Ignoring that the GHCJS boot package "syb" has a different version, 0.5.1, than the resolver's wanted version, 0.6
Ignoring that the GHCJS boot package "stm" has a different version, 2.4.4, than the resolver's wanted version, 2.4.4.1
Ignoring that the GHCJS boot package "parallel" has a different version, 3.2.0.6, than the resolver's wanted version, 3.2.1.0
Ignoring that the GHCJS boot package "dlist" has a different version, 0.7.1.1, than the resolver's wanted version, 0.7.1.2
Ignoring that the GHCJS boot package "pretty" has a different version, 1.1.3.2, than the resolver's wanted version, 1.1.2.0
Ignoring that the GHCJS boot package "containers" has a different version, 0.5.6.3, than the resolver's wanted version, 0.5.6.2
Ignoring that the GHCJS boot package "transformers" has a different version, 0.4.3.0, than the resolver's wanted version, 0.4.2.0
react-flux-1.0.7: configure
Progress: 1/2
--  While building package react-flux-1.0.7 using:
      /Users/rune/.stack/setup-exe-cache/x86_64-osx/setup-Simple-Cabal-1.22.8.0-ghcjs-0.2.0_ghc-7.10.3 --builddir=.stack-work/dist/x86_64-osx/Cabal-1.22.8.0_ghcjs configure --with-ghc=/Users/rune/.stack/programs/x86_64-osx/ghc-7.10.3/bin/ghc --with-ghc-pkg=/Users/rune/.stack/programs/x86_64-osx/ghc-7.10.3/bin/ghc-pkg --with-ghcjs=/Users/rune/.stack/programs/x86_64-osx/ghcjs-0.2.0.20160414_ghc-7.10.3/bin/ghcjs --with-ghcjs-pkg=/Users/rune/.stack/programs/x86_64-osx/ghcjs-0.2.0.20160414_ghc-7.10.3/bin/ghcjs-pkg --user --package-db=clear --package-db=global --package-db=/Users/rune/.stack/snapshots/x86_64-osx/lts-5.12/ghcjs-0.2.0_ghc-7.10.3/pkgdb --package-db=/Users/rune/IdeaProjects/react-flux-example/.stack-work/install/x86_64-osx/lts-5.12/ghcjs-0.2.0_ghc-7.10.3/pkgdb --libdir=/Users/rune/IdeaProjects/react-flux-example/.stack-work/install/x86_64-osx/lts-5.12/ghcjs-0.2.0_ghc-7.10.3/lib --bindir=/Users/rune/IdeaProjects/react-flux-example/.stack-work/install/x86_64-osx/lts-5.12/ghcjs-0.2.0_ghc-7.10.3/bin --datadir=/Users/rune/IdeaProjects/react-flux-example/.stack-work/install/x86_64-osx/lts-5.12/ghcjs-0.2.0_ghc-7.10.3/share --libexecdir=/Users/rune/IdeaProjects/react-flux-example/.stack-work/install/x86_64-osx/lts-5.12/ghcjs-0.2.0_ghc-7.10.3/libexec --sysconfdir=/Users/rune/IdeaProjects/react-flux-example/.stack-work/install/x86_64-osx/lts-5.12/ghcjs-0.2.0_ghc-7.10.3/etc --docdir=/Users/rune/IdeaProjects/react-flux-example/.stack-work/install/x86_64-osx/lts-5.12/ghcjs-0.2.0_ghc-7.10.3/doc/react-flux-1.0.7 --htmldir=/Users/rune/IdeaProjects/react-flux-example/.stack-work/install/x86_64-osx/lts-5.12/ghcjs-0.2.0_ghc-7.10.3/doc/react-flux-1.0.7 --haddockdir=/Users/rune/IdeaProjects/react-flux-example/.stack-work/install/x86_64-osx/lts-5.12/ghcjs-0.2.0_ghc-7.10.3/doc/react-flux-1.0.7 --dependency=aeson=aeson-0.9.0.1-3e4c2dfde782b48a8a098e80659095ee --dependency=base=base-4.8.0.0-dfcb8827e626c492adcc37fd2bd3d617 --dependency=bytestring=bytestring-0.10.6.0-a1a05efc592151eed31f4724b5c205e3 --dependency=deepseq=deepseq-1.4.1.1-e7d802656897717e165b2322433feb97 --dependency=ghcjs-base=ghcjs-base-0.2.0.0-f402f58916a3d7838505c8492427e419 --dependency=mtl=mtl-2.2.1-4907c4f5756261215301172cbc277371 --dependency=template-haskell=template-haskell-2.10.0.0-cb2294177ae9de2345fd1f894e1f0ac8 --dependency=text=text-1.2.1.1-b3d87cee4fab4c8c344b1910f27b08fa --dependency=time=time-1.5.0.1-de429c49aaf85f3623fb1238cf262e08 --dependency=unordered-containers=unordered-containers-0.2.5.1-2d2223b333dd47e2d219722c04d57e8d --ghcjs
    Process exited with code: ExitFailure 1
    Logs have been written to: /Users/rune/IdeaProjects/react-flux-example/.stack-work/logs/react-flux-1.0.7.log

    Configuring react-flux-1.0.7...
    setup-Simple-Cabal-1.22.8.0-ghcjs-0.2.0_ghc-7.10.3:
    .stack-work/dist/x86_64-osx/Cabal-1.22.8.0_ghcjs/: does not exist

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/7.4.0/bin/node" "/usr/local/bin/npm" "run-script" "make"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! react-flux-example@1.0.0 make: `./bundle.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-flux-example@1.0.0 make script './bundle.sh'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-flux-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./bundle.sh
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-flux-example
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-flux-example
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rune/IdeaProjects/react-flux-example/npm-debug.log

$ cat npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/7.4.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run-script',
1 verbose cli   'make' ]
2 info using npm@4.0.5
3 info using node@v7.4.0
4 verbose run-script [ 'premake', 'make', 'postmake' ]
5 info lifecycle react-flux-example@1.0.0~premake: react-flux-example@1.0.0
6 silly lifecycle react-flux-example@1.0.0~premake: no script for premake, continuing
7 info lifecycle react-flux-example@1.0.0~make: react-flux-example@1.0.0
8 verbose lifecycle react-flux-example@1.0.0~make: unsafe-perm in lifecycle true
9 verbose lifecycle react-flux-example@1.0.0~make: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/rune/IdeaProjects/react-flux-example/node_modules/.bin:/Users/rune/Downloads/google-cloud-sdk/bin:/Users/rune/.stack/programs/x86_64-osx/ghc-7.10.3/bin:/Users/rune/.local/bin:/Library/TeX/texbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle react-flux-example@1.0.0~make: CWD: /Users/rune/IdeaProjects/react-flux-example
11 silly lifecycle react-flux-example@1.0.0~make: Args: [ '-c', './bundle.sh' ]
12 silly lifecycle react-flux-example@1.0.0~make: Returned: code: 1  signal: null
13 info lifecycle react-flux-example@1.0.0~make: Failed to exec make script
14 verbose stack Error: react-flux-example@1.0.0 make: `./bundle.sh`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid react-flux-example@1.0.0
16 verbose cwd /Users/rune/IdeaProjects/react-flux-example
17 error Darwin 15.4.0
18 error argv "/usr/local/Cellar/node/7.4.0/bin/node" "/usr/local/bin/npm" "run-script" "make"
19 error node v7.4.0
20 error npm  v4.0.5
21 error code ELIFECYCLE
22 error react-flux-example@1.0.0 make: `./bundle.sh`
22 error Exit status 1
23 error Failed at the react-flux-example@1.0.0 make script './bundle.sh'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the react-flux-example package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ./bundle.sh
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs react-flux-example
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls react-flux-example
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by agrafix** [comment]
This looks like an instance of https://github.com/commercialhaskell/stack/issues/2495

**Comment by runeksvendsen** [comment]
I just tried building on a Linux box and this worked fine, so it must be an OSX issue.

It doesn't look like commercialhaskell/stack#2495 as far as I can see. I get no messages about missing packages or modules, only stack looking inside a `.stack-work/dist/` that is empty, while configuring `react-flux`.

Before I ran `npm run-script make` on Linux, there weren't any files in `.stack-work/dist/` either, so `stack build` seems to be missing a step on OSX that happens on Linux (populating `.stack-work/dist/` with something).

Linux log:

```shell
$ npm run-script make

> react-flux-example@1.0.0 make /home/rune/code/react-flux-example
> ./bundle.sh

Stack build ...
Ignoring that the GHCJS boot package "scientific" has a different version, 0.3.3.8, than the resolver's wanted version, 0.3.4.6
Ignoring that the GHCJS boot package "case-insensitive" has a different version, 1.2.0.4, than the resolver's wanted version, 1.2.0.6
Ignoring that the GHCJS boot package "hashable" has a different version, 1.2.3.2, than the resolver's wanted version, 1.2.4.0
Ignoring that the GHCJS boot package "async" has a different version, 2.0.1.6, than the resolver's wanted version, 2.1.0
Ignoring that the GHCJS boot package "text" has a different version, 1.2.1.1, than the resolver's wanted version, 1.2.2.1
Ignoring that the GHCJS boot package "syb" has a different version, 0.5.1, than the resolver's wanted version, 0.6
Ignoring that the GHCJS boot package "stm" has a different version, 2.4.4, than the resolver's wanted version, 2.4.4.1
Ignoring that the GHCJS boot package "parallel" has a different version, 3.2.0.6, than the resolver's wanted version, 3.2.1.0
Ignoring that the GHCJS boot package "dlist" has a different version, 0.7.1.1, than the resolver's wanted version, 0.7.1.2
Ignoring that the GHCJS boot package "pretty" has a different version, 1.1.3.2, than the resolver's wanted version, 1.1.2.0
Ignoring that the GHCJS boot package "containers" has a different version, 0.5.6.3, than the resolver's wanted version, 0.5.6.2
Ignoring that the GHCJS boot package "transformers" has a different version, 0.4.3.0, than the resolver's wanted version, 0.4.2.0
react-flux-1.0.7: configure
react-flux-1.0.7: build
react-flux-1.0.7: copy/register
react-flux-example-0.1.0.0: configure (exe)
Configuring react-flux-example-0.1.0.0...
react-flux-example-0.1.0.0: build (exe)
Preprocessing executable 'react-flux-example' for
react-flux-example-0.1.0.0...
[1 of 3] Compiling Ajax             ( app/Ajax.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.8.0_ghcjs/build/react-flux-example/react-flux-example-tmp/Ajax.js_o )
[2 of 3] Compiling Canvas           ( app/Canvas.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.8.0_ghcjs/build/react-flux-example/react-flux-example-tmp/Canvas.js_o )
[3 of 3] Compiling Main             ( app/Main.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.8.0_ghcjs/build/react-flux-example/react-flux-example-tmp/Main.js_o )
Linking Template Haskell (Ajax,Canvas,ThRunner1)
Linking Template Haskell (Ajax,Canvas,ThRunner2)
Linking Template Haskell (Ajax,Canvas,ThRunner3)
Linking .stack-work/dist/x86_64-linux/Cabal-1.22.8.0_ghcjs/build/react-flux-example/react-flux-example.jsexe (Ajax,Canvas,Main)
react-flux-example-0.1.0.0: copy/register
Installing executable(s) in
/home/rune/code/react-flux-example/.stack-work/install/x86_64-linux/lts-5.12/ghcjs-0.2.0_ghc-7.10.3/bin
Warning: the following files would be used as linker inputs, but linking is not being done: .stack-work/dist/x86_64-linux/Cabal-1.22.8.0_ghcjs/build/react-flux-example/react-flux-example
Completed 2 action(s).
Adding stubs ...
Building dependencies ... 
Building production bundle ... 
(node) util.print is deprecated. Use console.log instead.
Copying needed css files ... 
Generating index.html ...
```

OSX logs:
```shell
rune@Runes-MacBook-Pro:~/IdeaProjects/react-flux-example$ npm run-script make

> react-flux-example@1.0.0 make /Users/rune/IdeaProjects/react-flux-example
> ./bundle.sh

Stack build ...
Ignoring that the GHCJS boot package "scientific" has a different version, 0.3.3.8, than the resolver's wanted version, 0.3.4.6
Ignoring that the GHCJS boot package "case-insensitive" has a different version, 1.2.0.4, than the resolver's wanted version, 1.2.0.6
Ignoring that the GHCJS boot package "hashable" has a different version, 1.2.3.2, than the resolver's wanted version, 1.2.4.0
Ignoring that the GHCJS boot package "async" has a different version, 2.0.1.6, than the resolver's wanted version, 2.1.0
Ignoring that the GHCJS boot package "text" has a different version, 1.2.1.1, than the resolver's wanted version, 1.2.2.1
Ignoring that the GHCJS boot package "syb" has a different version, 0.5.1, than the resolver's wanted version, 0.6
Ignoring that the GHCJS boot package "stm" has a different version, 2.4.4, than the resolver's wanted version, 2.4.4.1
Ignoring that the GHCJS boot package "parallel" has a different version, 3.2.0.6, than the resolver's wanted version, 3.2.1.0
Ignoring that the GHCJS boot package "dlist" has a different version, 0.7.1.1, than the resolver's wanted version, 0.7.1.2
Ignoring that the GHCJS boot package "pretty" has a different version, 1.1.3.2, than the resolver's wanted version, 1.1.2.0
Ignoring that the GHCJS boot package "containers" has a different version, 0.5.6.3, than the resolver's wanted version, 0.5.6.2
Ignoring that the GHCJS boot package "transformers" has a different version, 0.4.3.0, than the resolver's wanted version, 0.4.2.0
react-flux-1.0.7: configure
Progress: 1/2
--  While building package react-flux-1.0.7 using:
      /Users/rune/.stack/setup-exe-cache/x86_64-osx/setup-Simple-Cabal-1.22.8.0-ghcjs-0.2.0_ghc-7.10.3 --builddir=.stack-work/dist/x86_64-osx/Cabal-1.22.8.0_ghcjs configure --with-ghc=/Users/rune/.stack/programs/x86_64-osx/ghc-7.10.3/bin/ghc --with-ghc-pkg=/Users/rune/.stack/programs/x86_64-osx/ghc-7.10.3/bin/ghc-pkg --with-ghcjs=/Users/rune/.stack/programs/x86_64-osx/ghcjs-0.2.0.20160414_ghc-7.10.3/bin/ghcjs --with-ghcjs-pkg=/Users/rune/.stack/programs/x86_64-osx/ghcjs-0.2.0.20160414_ghc-7.10.3/bin/ghcjs-pkg --user --package-db=clear --package-db=global --package-db=/Users/rune/.stack/snapshots/x86_64-osx/lts-5.12/ghcjs-0.2.0_ghc-7.10.3/pkgdb --package-db=/Users/rune/IdeaProjects/react-flux-example/.stack-work/install/x86_64-osx/lts-5.12/ghcjs-0.2.0_ghc-7.10.3/pkgdb --libdir=/Users/rune/IdeaProjects/react-flux-example/.stack-work/install/x86_64-osx/lts-5.12/ghcjs-0.2.0_ghc-7.10.3/lib --bindir=/Users/rune/IdeaProjects/react-flux-example/.stack-work/install/x86_64-osx/lts-5.12/ghcjs-0.2.0_ghc-7.10.3/bin --datadir=/Users/rune/IdeaProjects/react-flux-example/.stack-work/install/x86_64-osx/lts-5.12/ghcjs-0.2.0_ghc-7.10.3/share --libexecdir=/Users/rune/IdeaProjects/react-flux-example/.stack-work/install/x86_64-osx/lts-5.12/ghcjs-0.2.0_ghc-7.10.3/libexec --sysconfdir=/Users/rune/IdeaProjects/react-flux-example/.stack-work/install/x86_64-osx/lts-5.12/ghcjs-0.2.0_ghc-7.10.3/etc --docdir=/Users/rune/IdeaProjects/react-flux-example/.stack-work/install/x86_64-osx/lts-5.12/ghcjs-0.2.0_ghc-7.10.3/doc/react-flux-1.0.7 --htmldir=/Users/rune/IdeaProjects/react-flux-example/.stack-work/install/x86_64-osx/lts-5.12/ghcjs-0.2.0_ghc-7.10.3/doc/react-flux-1.0.7 --haddockdir=/Users/rune/IdeaProjects/react-flux-example/.stack-work/install/x86_64-osx/lts-5.12/ghcjs-0.2.0_ghc-7.10.3/doc/react-flux-1.0.7 --dependency=aeson=aeson-0.9.0.1-3e4c2dfde782b48a8a098e80659095ee --dependency=base=base-4.8.0.0-dfcb8827e626c492adcc37fd2bd3d617 --dependency=bytestring=bytestring-0.10.6.0-a1a05efc592151eed31f4724b5c205e3 --dependency=deepseq=deepseq-1.4.1.1-e7d802656897717e165b2322433feb97 --dependency=ghcjs-base=ghcjs-base-0.2.0.0-f402f58916a3d7838505c8492427e419 --dependency=mtl=mtl-2.2.1-4907c4f5756261215301172cbc277371 --dependency=template-haskell=template-haskell-2.10.0.0-cb2294177ae9de2345fd1f894e1f0ac8 --dependency=text=text-1.2.1.1-b3d87cee4fab4c8c344b1910f27b08fa --dependency=time=time-1.5.0.1-de429c49aaf85f3623fb1238cf262e08 --dependency=unordered-containers=unordered-containers-0.2.5.1-2d2223b333dd47e2d219722c04d57e8d --ghcjs
    Process exited with code: ExitFailure 1
    Logs have been written to: /Users/rune/IdeaProjects/react-flux-example/.stack-work/logs/react-flux-1.0.7.log

    Configuring react-flux-1.0.7...
    setup-Simple-Cabal-1.22.8.0-ghcjs-0.2.0_ghc-7.10.3:
    .stack-work/dist/x86_64-osx/Cabal-1.22.8.0_ghcjs/: does not exist

```

**Comment by agrafix** [comment]
For me this works on OSX:

```
# athiemann @ goldfinger.local in ~/devel/react-flux-example on git:master ✔︎  [13:30:19]
λ ./bundle.sh
Stack build ...
Ignoring that the GHCJS boot package "scientific" has a different version, 0.3.3.8, than the resolver's wanted version, 0.3.4.6
Ignoring that the GHCJS boot package "case-insensitive" has a different version, 1.2.0.4, than the resolver's wanted version, 1.2.0.6
Ignoring that the GHCJS boot package "hashable" has a different version, 1.2.3.2, than the resolver's wanted version, 1.2.4.0
Ignoring that the GHCJS boot package "async" has a different version, 2.0.1.6, than the resolver's wanted version, 2.1.0
Ignoring that the GHCJS boot package "text" has a different version, 1.2.1.1, than the resolver's wanted version, 1.2.2.1
Ignoring that the GHCJS boot package "syb" has a different version, 0.5.1, than the resolver's wanted version, 0.6
Ignoring that the GHCJS boot package "stm" has a different version, 2.4.4, than the resolver's wanted version, 2.4.4.1
Ignoring that the GHCJS boot package "parallel" has a different version, 3.2.0.6, than the resolver's wanted version, 3.2.1.0
Ignoring that the GHCJS boot package "dlist" has a different version, 0.7.1.1, than the resolver's wanted version, 0.7.1.2
Ignoring that the GHCJS boot package "pretty" has a different version, 1.1.3.2, than the resolver's wanted version, 1.1.2.0
Ignoring that the GHCJS boot package "containers" has a different version, 0.5.6.3, than the resolver's wanted version, 0.5.6.2
Ignoring that the GHCJS boot package "transformers" has a different version, 0.4.3.0, than the resolver's wanted version, 0.4.2.0
react-flux-example-0.1.0.0: configure (exe)
Configuring react-flux-example-0.1.0.0...
react-flux-example-0.1.0.0: build (exe)
Preprocessing executable 'react-flux-example' for
react-flux-example-0.1.0.0...
[3 of 3] Compiling Main             ( app/Main.hs, .stack-work/dist/x86_64-osx/Cabal-1.22.8.0_ghcjs/build/react-flux-example/react-flux-example-tmp/Main.js_o )
Linking Template Haskell (Ajax,Canvas,ThRunner1)
Linking Template Haskell (Ajax,Canvas,ThRunner2)
Linking Template Haskell (Ajax,Canvas,ThRunner3)
Linking .stack-work/dist/x86_64-osx/Cabal-1.22.8.0_ghcjs/build/react-flux-example/react-flux-example.jsexe (Ajax,Canvas,Main)
react-flux-example-0.1.0.0: copy/register
Installing executable(s) in
/Users/athiemann/devel/react-flux-example/.stack-work/install/x86_64-osx/lts-5.12/ghcjs-0.2.0_ghc-7.10.3/bin
Warning: the following files would be used as linker inputs, but linking is not being done: .stack-work/dist/x86_64-osx/Cabal-1.22.8.0_ghcjs/build/react-flux-example/react-flux-example
Adding stubs ...
Building dependencies ...
Building production bundle ...
(node:10679) DeprecationWarning: util.print is deprecated. Use console.log instead.
Copying needed css files ...
Generating index.html ...
```

The warning `Warning: the following files would be used as linker inputs, but linking is not being done: .stack-work/dist/x86_64-osx/Cabal-1.22.8.0_ghcjs/build/react-flux-example/react-flux-example` is interesting, but not sure if it has something todo with the issue.

Which stack version? I'm on 1.3.0 (stack) and 6.1.0 (node). Maybe try downgrading to 6.1.0 for node?

**Comment by agrafix** [comment]
@runeksvendsen did downgrading node fix the issue for you?

**Comment by runeksvendsen** [comment]
Hello again. I completely forgot about this. I just installed node 6.1.0 and this fixed it. I also upgraded to stack 1.3.2, but it didn't work until I downgraded node, so I'm pretty sure this is the fix. Thank you!
